[tool.poetry]
name = "batchobfuscator"
version = "0.1.0"
description = "A simple batch obfuscator made in python"
authors = ["Codaxy <codaxy@sylph.dev>"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
